### ISSUE TITLE
Having this extension enabled causes a 500 error on all payments

### ISSUE THREAD

**Issue by caliginous** [veda-consulting/uk.co.vedaconsulting.payment.ukdirectdebit#56]
I'm using the latest civicrm on wordpress.  I get this error in my apache log when trying to make any payment (credit card, debit card, offline payments etc):

[Wed Apr 05 14:54:49.187955 2017] [:error] [pid 14208] [client 86.145.124.146:64750] PHP Fatal error:  Uncaught Error: Call to undefined method CRM_Member_BAO_Membership::renewMembership() in /var/www/html/wp-content/plugins/files/civicrm/ext/uk.co.vedaconsulting.payment.ukdirectdebit-master/CRM/Contribute/Form/Contribution/Confirm.php:1512\nStack trace:\n#0 /var/www/html/wp-content/plugins/files/civicrm/ext/uk.co.vedaconsulting.payment.ukdirectdebit-master/CRM/Contribute/Form/Contribution/Confirm.php(1378): CRM_Contribute_Form_Contribution_Confirm->postProcessMembership(Array, '2', Object(CRM_Contribute_Form_Contribution_Confirm), Array, Array, Array, Array, Array, false, NULL, true, '2', Array, 0, true)\n#1 /var/www/html/wp-content/plugins/files/civicrm/ext/uk.co.vedaconsulting.payment.ukdirectdebit-master/CRM/Contribute/Form/Contribution/Confirm.php(2314): CRM_Contribute_Form_Contribution_Confirm->processMembership(Array, '2', Array, Array, Array, Array, 0)\n#2 /var/www/html/wp-content/plugins/files/civicrm/ext/uk.co.vedaconsulting.payment.ukdirectdebit-master/CRM/Contribute/Form/Contribution/Confirm.php(2188): in /var/www/html/wp-content/plugins/files/civicrm/ext/uk.co.vedaconsulting.payment.ukdirectdebit-master/CRM/Contribute/Form/Contribution/Confirm.php on line 1512, referer: http://178.62.76.221/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fcontribute%2Ftransact&_qf_Confirm_display=true&qfKey=d3f41534876c292dcfbb6c49bf3a7215_3845

After disabling this extension, everything works again.

**Comment by xurizaemon** [comment]
This is a duplicate of #53

**Comment by mattwire** [comment]
For CiviCRM 4.7+ please use the rewritten smartdebit extension here: https://github.com/mattwire/uk.co.vedaconsulting.smartdebit
